### ISSUE TITLE
grabbing objects from my array and working them into my exciting jQuery code.

### ISSUE THREAD

**Issue by shotbyabel** [shotbyabel/Abel_Photographic_Memory_Game#2]
I've gotten some suggestions about how to get this started but I am just confused. 

I have different objects that I need to plug into different photo slides. I am not completely sure on how to start this.  I have a total of 10 photos that will loop at least once but the information text information and buttons that need to be display on them contain different things. Do i make a for loop of them first?..  Phil suggested (if I recall correctly) "Write a function that adds photos and click events". I already have a click functions with jQuery that I think I can plug in. not entirely sure how to grab some of these button objects from my array and have them work with the jQuery. I also don't know how I will incorporate this loop into my title page and final score page.

**Comment by stanleycyang** [comment]
quizPhotos.forEach(function(element, index){
    console.log(element);
})

**Comment by stanleycyang** [comment]
Reword this issue to concisely say exactly what the procedural algorithm should, and where is it currently not functioning as expected. 

Or, if you need help on the direction of where to go, write a concise explanation of your procedural algorithm.

**Comment by ghost** [comment]
Hi Abel,

Come talk to me if you'd like to check in about your progress. Closes #2.
